route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-notifications'

receivers:
  - name: 'webhook-notifications'
    webhook_configs:
      - url: 'https://webhook.site/266834e3-dbb6-45a8-b40e-64f5db345ee1'
        send_resolved: true
        http_config:
          follow_redirects: true
          tls_config:
            insecure_skip_verify: true
