receivers:
  - name: 'default-receiver'
    slack_configs:
    - channel: '#alerts'
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
